import console from "console";
import fs from "fs-extra";

console.log("CREATING WARNING README");

fs.writeFileSync(
  "./lib/README.md",
  `
# WARNING! Autogenerated code

This directory and all its files is generated from the original [nanostores source code](https://github.com/nanostores/nanostores) using [TypeScriptToLua](https://typescripttolua.github.io/).

Only small modifications are made in the transformation process to ensure a clean build into lua. Please see the [../scripts](../scripts) folder for more.
`
);
